### ISSUE TITLE
在主界面左右滑动时，有时遇到NullPointerException强退的问题

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#14]
准确的重现方法不明，但是在移动（较慢的）网络下，加载页面时左右滑动的话，触发的可能性较大。
日志：
```
01-28 00:28:55.145    3227-3227/com.optimalorange.cooltechnologies D/AndroidRuntime﹕ Shutting down VM
01-28 00:28:55.145    3227-3227/com.optimalorange.cooltechnologies W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x419a7ce0)
01-28 00:28:55.165    3227-3227/com.optimalorange.cooltechnologies E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.optimalorange.cooltechnologies, PID: 3227
    java.lang.NullPointerException
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2946)
            at android.view.View.draw(View.java:14492)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.View.draw(View.java:14206)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2959)
            at android.view.View.draw(View.java:14492)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.View.draw(View.java:14206)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13381)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.View.draw(View.java:14206)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13381)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.View.draw(View.java:14206)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14492)
            at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:381)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.View.draw(View.java:14206)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14492)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2587)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13428)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2380)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2252)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
01-28 00:28:57.185    3227-3243/com.optimalorange.cooltechnologies D/Volley﹕ [225] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://openapi.youku.com/v2/videos/by_category.json?client_id=d407654cbc2f4838&category=%E7%A7%91%E6%8A%80&period=week&orderby=view-count&page=1 0xe8050afe NORMAL 47> [lifetime=3193], [size=14971], [rc=200], [retryCount=0]
```

**Comment by Bai-Jie** [comment]
其他人遇到的类似情况，可以参考：
http://stackoverflow.com/questions/23038131/nullpointerexception-on-dispatchdraw-with-viewpager-in-nested-fragment-with-page

**Comment by Bai-Jie** [comment]
一种准确的重现方法：
commit a53beb8ba458bf66f8ce4a5e6461597cc4f94bb2 版本下，在注销状态下，点击收藏页面的“刷新”菜单项，再向左划到热门页面，必然会遇到此bug。
