### ISSUE TITLE
收藏中不断进行刷新会有异常

### ISSUE THREAD

**Issue by Zhou-Peican** [OptimalOrange/CoolTechnologies#16]

**Comment by Bai-Jie** [comment]
日志：
```
02-22 16:20:32.151    7985-7985/com.optimalorange.cooltechnologies E/Trace﹕ error opening trace file: No such file or directory (2)
02-22 16:20:32.151    7985-7985/com.optimalorange.cooltechnologies D/ActivityThread﹕ setTargetHeapUtilization:0.25
02-22 16:20:32.151    7985-7985/com.optimalorange.cooltechnologies D/ActivityThread﹕ setTargetHeapIdealFree:8388608
02-22 16:20:32.151    7985-7985/com.optimalorange.cooltechnologies D/ActivityThread﹕ setTargetHeapConcurrentStart:2097152
02-22 16:20:32.201    7985-7985/com.optimalorange.cooltechnologies E/AdFireWallNative﹕ AdFrieWall JNI_OnLoad
02-22 16:20:32.201    7985-7985/com.optimalorange.cooltechnologies E/AdFireWallNative﹕ AdFireWall JNI_OnLoad done.
02-22 16:20:32.281    7985-7985/com.optimalorange.cooltechnologies W/IconCustomizer﹕ can't load transform_config.xml
02-22 16:20:32.591    7985-7985/com.optimalorange.cooltechnologies I/Adreno200-EGL﹕ <qeglDrvAPI_eglInitialize:299>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_REL_RB1.04.01.01.06.041_msm8660_surf_JB_REL_RB1.2_Merge_release_AU (Merge)
    Build Date: 11/05/12 Mon
    Local Branch: mybranch425650
    Remote Branch: quic/jb_rel_rb1.2
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_JB_REL_RB1.04.01.01.06.041 +  NOTHING
02-22 16:20:34.301    7985-7989/com.optimalorange.cooltechnologies D/dalvikvm﹕ GC_CONCURRENT freed 6612K, 49% free 7854K/15363K, paused 14ms+14ms, total 89ms
02-22 16:20:34.501    7985-8006/com.optimalorange.cooltechnologies D/dalvikvm﹕ GC_FOR_ALLOC freed 472K, 49% free 7937K/15363K, paused 31ms, total 31ms
02-22 16:20:38.441    7985-7985/com.optimalorange.cooltechnologies W/InputEventReceiver﹕ Attempted to finish an input event but the input event receiver has already been disposed.
02-22 16:20:40.081    7985-7989/com.optimalorange.cooltechnologies D/dalvikvm﹕ GC_CONCURRENT freed 2846K, 43% free 9272K/16263K, paused 12ms+15ms, total 107ms
02-22 16:20:43.461    7985-7989/com.optimalorange.cooltechnologies D/dalvikvm﹕ GC_CONCURRENT freed 5763K, 41% free 9803K/16455K, paused 12ms+16ms, total 107ms
02-22 16:20:43.521    7985-7985/com.optimalorange.cooltechnologies E/InputEventReceiver﹕ Exception dispatching input event.
02-22 16:20:43.521    7985-7985/com.optimalorange.cooltechnologies E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
02-22 16:20:43.541    7985-7985/com.optimalorange.cooltechnologies E/MessageQueue-JNI﹕ java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3592)
            at android.view.View.dispatchTouchEvent(View.java:7216)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2283)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2018)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2020)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1470)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2471)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1968)
            at android.view.View.dispatchPointerEvent(View.java:7396)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3251)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3196)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4238)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4217)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4309)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:4819)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
02-22 16:20:43.541    7985-7985/com.optimalorange.cooltechnologies W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41c2d360)
02-22 16:20:43.701    7985-7985/com.optimalorange.cooltechnologies E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3592)
            at android.view.View.dispatchTouchEvent(View.java:7216)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2283)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2018)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2020)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1470)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2471)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1968)
            at android.view.View.dispatchPointerEvent(View.java:7396)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3251)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3196)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4238)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4217)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4309)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:4819)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Leaking** [comment]
这个bug是有什么引起的，，我的项目部分用户好像也有，但是我重现不了

**Comment by bai-jie** [comment]
To @Leaking
我个人理解（没好好研究源代码），修改DataSet而没有notify，使用adapter的ListView之类的，可能无法及时知道DataSet结构变了，而仍然使用了旧的count（Adapter.getCount()，数据不一致）。例如像这里commit 80b33d775c2f352ccbecbfdc01fd6b2dc615bfcd 这处，修改DataSet使其count变为0，而旧的count大于0，导致IndexOutOfBoundsException就不奇怪了。
