### ISSUE TITLE
ShowVideoDetailActivity遇NullPointerException

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#75]
异常信息：

```
11-29 20:50:57.930 19545-19545/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17915: Landroid/support/v7/widget/RecyclerView$ViewHolder;.unScrap ()V
11-29 20:50:58.630 19545-19547/com.optimalorange.cooltechnologies D/dalvikvm: GC_CONCURRENT freed 3595K, 25% free 14272K/18951K, paused 2ms+12ms, total 71ms
11-29 20:51:02.140 19545-19545/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 22563: Lcom/optimalorange/cooltechnologies/network/SimpleRequest;.finish (Ljava/lang/String;)V
11-29 20:51:33.220 19545-19547/com.optimalorange.cooltechnologies D/dalvikvm: GC_CONCURRENT freed 4907K, 28% free 15563K/21447K, paused 13ms+28ms, total 142ms
11-29 20:51:56.660 19545-19632/com.optimalorange.cooltechnologies E/Volley: [1829] BasicNetwork.performRequest: Unexpected response code 400 for https://openapi.youku.com/v2/videos/show.json?client_id=f82d93e4aa1b04e6&video_id=XMTM5NTQ0MDI5Ng%3D%3D
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err: java.lang.RuntimeException: com.android.volley.ServerError
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.optimalorange.cooltechnologies.ui.ShowVideoDetailActivity$VideoDetailRequestHandler.onErrorResponse(ShowVideoDetailActivity.java:259)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.volley.Request.deliverError(Request.java:598)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at android.os.Looper.loop(Looper.java:137)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4819)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-29 20:51:56.690 19545-19545/com.optimalorange.cooltechnologies W/System.err: Caused by: com.android.volley.ServerError
11-29 20:51:56.700 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
11-29 20:51:56.700 19545-19545/com.optimalorange.cooltechnologies W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
11-29 20:51:57.730 19545-19545/com.optimalorange.cooltechnologies W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4132b360)
11-29 20:51:57.910 19545-19545/com.optimalorange.cooltechnologies E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    java.lang.NullPointerException
                                                                                        at com.optimalorange.cooltechnologies.ui.ShowVideoDetailActivity.buildCreateFavoriteRequest(ShowVideoDetailActivity.java:229)
                                                                                        at com.optimalorange.cooltechnologies.ui.ShowVideoDetailActivity.onOptionsItemSelected(ShowVideoDetailActivity.java:204)
                                                                                        at android.app.Activity.onMenuItemSelected(Activity.java:2609)
                                                                                        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
                                                                                        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                                                        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:68)
                                                                                        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:172)
                                                                                        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
                                                                                        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
                                                                                        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                                        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                                                        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
                                                                                        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
                                                                                        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
                                                                                        at android.view.View.performClick(View.java:4171)
                                                                                        at android.view.View$PerformClick.run(View.java:17097)
                                                                                        at android.os.Handler.handleCallback(Handler.java:615)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4819)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Bai-Jie** [comment]
重现方式：
快速切换页面，如快速频繁进入退出。
