### ISSUE TITLE
ListVideosFragment遇NullPointerException

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#76]
异常信息：

```
11-29 22:04:11.570 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17897: Landroid/support/v7/widget/RecyclerView$ViewHolder;.isScrap ()Z
11-29 22:04:11.570 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17871: Landroid/support/v7/widget/RecyclerView$ViewHolder;.addFlags (I)V
11-29 22:04:11.570 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17919: Landroid/support/v7/widget/RecyclerView$ViewHolder;.wasReturnedFromScrap ()Z
11-29 22:04:11.570 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17889: Landroid/support/v7/widget/RecyclerView$ViewHolder;.getUnmodifiedPayloads ()Ljava/util/List;
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17913: Landroid/support/v7/widget/RecyclerView$ViewHolder;.stopIgnoring ()V
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17898: Landroid/support/v7/widget/RecyclerView$ViewHolder;.isTmpDetached ()Z
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17894: Landroid/support/v7/widget/RecyclerView$ViewHolder;.isInvalid ()Z
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17910: Landroid/support/v7/widget/RecyclerView$ViewHolder;.setScrapContainer (Landroid/support/v7/widget/RecyclerView$Recycler;Z)V
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17906: Landroid/support/v7/widget/RecyclerView$ViewHolder;.resetInternal ()V
11-29 22:04:11.580 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: VFY: unable to resolve virtual method 17915: Landroid/support/v7/widget/RecyclerView$ViewHolder;.unScrap ()V
11-29 22:04:13.830 11068-11069/com.optimalorange.cooltechnologies D/dalvikvm: GC_CONCURRENT freed 4288K, 37% free 10486K/16519K, paused 12ms+6ms, total 149ms
11-29 22:04:22.510 11068-11068/com.optimalorange.cooltechnologies I/Choreographer: Skipped 114 frames!  The application may be doing too much work on its main thread.
11-29 22:04:22.740 11068-11068/com.optimalorange.cooltechnologies W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4132b360)
11-29 22:04:23.690 11068-11068/com.optimalorange.cooltechnologies E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    java.lang.NullPointerException
                                                                                        at com.optimalorange.cooltechnologies.ui.fragment.ListVideosFragment.onCreateOptionsMenu(ListVideosFragment.java:391)
                                                                                        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2044)
                                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2114)
                                                                                        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
                                                                                        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                                        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                                        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
                                                                                        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
                                                                                        at android.os.Handler.handleCallback(Handler.java:615)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4819)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Bai-Jie** [comment]
重现方式：
快速切换页面，如主页快速最左最右切换。

**Comment by bai-jie** [comment]
难以重现
